### ISSUE TITLE
Error filtering by functional group

### ISSUE THREAD

**Issue by felipeZ** [nlesc-nano/flamingo#18]
Given the following candidates:
```csv
,smiles
0,CN1C=NC2=C1C(=O)N(C(=O)N2C)C
1,OC(=O)C1CNC2C3C4CC2C1N34
2,C1=CC=CC=C1
3,OC(=O)C1CNC2COC1(C2)C#C
4,CCO
5,CCCCCCCCC=CCCCCCCCC(=O)O
6,CC(=O)O
7,O=C(O)Cc1ccccc1
8,CC(C(=O)O)O
9,CC12C3C(=O)OCC14CC=C(C4)C32
```
When applying the filter:
```yaml
filters:
  include_functional_groups:
    - "C(=O)O[H]"
```
It returns the carboxylic acids and the esthers:
```
'O=C(O)C1CNC2C3CC4C2N4C13'
'C#CC12CC(CO1)NCC2C(=O)O'
 'CCCCCCCCC=CCCCCCCCC(=O)O' 
'CC(=O)O' 'O=C(O)Cc1ccccc1'
 'CC(O)C(=O)O'
 'CC12C3C(=O)OCC14CC=C(C4)C32'
```
