### ISSUE TITLE
Feature: filter one or more anchoring groups

### ISSUE THREAD

**Issue by felipeZ** [nlesc-nano/flamingo#43]
## Expected behavior
Currently, the input file can take the functional groups to include like:
```yml
  include_functional_groups:
    - "[CX3](=O)[OX2H1]"
    -  [NX3][CX3]=[CX3] 
```
A new keyword called `maximum` indicates whether `1` or more of those groups should be include. For examples, the input
```yml
  include_functional_groups:
    groups:
       - "[CX3](=O)[OX2H1]"
       -  [NX3][CX3]=[CX3] 
    maximum: 1
```
would Indicate that **at most** one carboxylic acids or one primary amine must be present. 
On  the other hand, the input:
```yml
  include_functional_groups:
    groups:
       - "[CX3](=O)[OX2H1]"
       -  [NX3][CX3]=[CX3]
     maximum: 2 
```
indicates that the following results are allowed:
* 1 or 2 Carboxylic acids
* 1 or 2 amines 
* 1 carboxylic acid and 1 amine are allowed.

**Notes:**
1.  `maximum: 1` would be the default
2. There would be a `groups` keyword subsection to declare the *smarts* functional groups
